import md5WasmTest from "../benchmarkTests/md5WasmTest";
import aesWasmTest from "../benchmarkTests/aesWasmTest";

const benchmarkDatasets = {
  md5: {
    data: "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
    testbench: md5WasmTest,
  },
  aes: {
    data: "hfdsajfjhkldsajlfk;jdsal;kjclnxzoivcdsjauifhjefdsafdsafkjndiksafiuejnkdasfkjasafdsaiunfjkcxzhnuirdsanjkcxznvjdsaoivcncxzjkvndsiuanvjkzxnvuihiundsiufhnuiadghreuiyhyiqnbbjksdfnvkjzaisdufhnka",
    testbench: aesWasmTest,
  },
};

export default benchmarkDatasets;
